### ISSUE TITLE
Unsupported keyword argument 'score_cast_func' to zrangebyscore()

### ISSUE THREAD

**Issue by fferrara** [jamesls/fakeredis#193] opened 2018-06-08 14:26 UTC
In the latest version of `redis-py`, [zrangebyscore() accepts a keyword argument called score_cast_func.](http://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.zrangebyscore)

Fakeredis [does not support it yet](https://github.com/jamesls/fakeredis/blob/master/fakeredis.py#L1630-L1631).

I'll do a PR ASAP.

**Comment by bmerry** [comment] 2018-06-08 14:38
There are two PRs already, but they're incomplete. You can probably save some time/effort by finishing what they started.

**Comment by bmerry** [comment] 2018-06-08 14:39
Closing because it's a duplicate of #44 (a complete PR would still be welcome though).

**Closed by bmerry** 2018-06-08 14:39 UTC

**Comment by fferrara** [comment] 2018-06-08 15:11
Sorry, I didn't check the open PRs. I ended up by making my own complete PR in #194 , with one test. Not sure if it's enough to be merged

**Comment by bmerry** [comment] 2018-06-08 19:10
Thanks, I'll take a look next week.
