### ISSUE TITLE
fakeredis doesn't work on Alpine linux because of lack of libc

### ISSUE THREAD

**Issue by szborows** [jamesls/fakeredis#227] opened 2018-12-07 11:12 UTC
Alpine Linux uses muslr instead of libc.

There were other issues for MacOS and Windows respectively: #107 #188 

Traceback:
```
Traceback:
tests/test_lib.py:1: in <module>
    import fakeredis
.tox/pylint-error/lib/python3.7/site-packages/fakeredis.py:105: in <module>
    raise ImportError('fakeredis: unable to find libc or equivalent')
E   ImportError: fakeredis: unable to find libc or equivalent
```

Edit:
image used: `python:3.7-alpine3.8`

**Comment by bmerry** [comment] 2018-12-08 21:00
This is a duplicate of #190. It's a limitation of Python on Alpine.

**Closed by bmerry** 2018-12-08 21:00 UTC
